# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['21.0']
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ErlGang/setup-erlang@v1.0.0
        with:
          otp-version: ${{ matrix.otp }}
      - name: Install rebar3
        run: |
          cd "$RUNNER_TEMP"
          mkdir bin
          wget -O bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
          chmod a+x bin/rebar3
          echo "${PWD}/bin" >> "$GITHUB_PATH"
      - run: ci_testing/start_xmpp_cluster.sh
      - run: ci_testing/run_test.sh
