# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Run this workflow every day
  schedule:
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['22.3.4', '21.3']
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ErlGang/setup-erlang@v1.0.0
        with:
          otp-version: ${{ matrix.otp }}
      - name: Install rebar3
        run: |
          cd "$RUNNER_TEMP"
          mkdir bin
          wget -O bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
          chmod a+x bin/rebar3
          echo "${PWD}/bin" >> "$GITHUB_PATH"
      - name: Update Mercutio dependencies
        run: rebar3 upgrade
      - name: Ensure that rebar.lock is updated in PR
        if: ${{ github.event_name == 'pull_request' }}
        run: git diff --quiet rebar.lock
      - name: Build Mercutio docker image
        run: ci_testing/build_mercutio_image.sh ${{matrix.otp}}
      - name: Start XMPP cluster (with connected Mercutio component) for testing
        run: ci_testing/start_xmpp_cluster.sh
      - name: Execute tests
        run: ci_testing/run_test.sh
